name: Matrix Learn
on: push
jobs:
    build:
        strategy:
            matrix:
                node-version: [12,14,16,18]
                os: [ubuntu-latest, windows-latest]
                include:
                    - node-version: 20
                      os: [ubuntu-latest]
                exclude:
                    - node-version: 12
                      os: ubuntu-latest
                    - node-version: 14
                      os: windows-latest
                    - node-version: 12
                      os: windows-latest
                    - node-version: 14
                      os: ubuntu-latest
        runs-on: ${{matrix.os}}
        steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Install NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: ${{matrix.node-version}}
        - name: Install Dependencies
          run: npm ci
        - name: Build Project
          run: npm run build