name: Reusable workflow
on: 
    workflow_call:
        inputs:
            artifact-name:
              description: Download the deployable files
              required: false
              default: dist
              type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Get build artifacts
          uses: actions/download-artifact@v4
          with:
            name: ${{ inputs.artifact-name}}
        - name: List files
          run: ls
        - name: Output contents
          run: ls
        - name: Deploy
          run: echo "Deploying..."